#!/bin/bash

#SBATCH -A snic2020-15-186
#SBATCH -p core
#SBATCH -n 15
#SBATCH -t 10:00:00
#SBATCH -J LinusTrinity

singularity exec /proj/snic2020-15-186/LinusBenchmark/Containers/Spades_latest.sif spades.py -1 /proj/snic2020-15-186/LinusBenchmark/data/HomoSap/Large1_ENCSR362HMX/sample1/homosapLarge1Left.fastq.gz  -2 /proj/snic2020-15-186/LinusBenchmark/data/HomoSap/Large1_ENCSR362HMX/sample1/homosapLarge2Right.fastq.gz -o /proj/snic2020-15-186/LinusBenchmark/output/outputSpades --rna
